---

- hosts: test
  become: yes
  gather_facts: no
  tasks:
    - name: Install python setup tools
      yum: name=python-setuptools
      tags: docker

    - name: Install Pypi
      easy_install: name=pip
      tags: docker

    - name: Install docker-py
      pip: name=docker-py
      tags: docker

    - name: Install Docker
      yum: name=docker state=latest
      tags: docker

    - lineinfile:
        path: /usr/lib/systemd/system/docker.service
        regexp: '^ExecStart=/usr/bin/dockerd-current'
        line: 'ExecStart=/usr/bin/dockerd-current -H tcp://0.0.0.0:2375 -H unix://var/run/docker.sock \'

    - name: Reload daemons
      action: shell systemctl daemon-reload

    - name: Start service Docker, if not running
      service:
        name: docker
        state: started
        enabled: yes
